name: 定时缓存

on:
  schedule:
  - cron: '0 12 * * *'

env:
  CHANNEL_ID: UCoLQZ4ZClFqVPCvvjuiUSRA

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: FedericoCarboni/setup-ffmpeg@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install python dependencies
      run: |
        python -m pip install requests base58 pycryptodomex

    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install node dependencies
      run: |
        npm install

    # - name: Build
    #   run: |
    #     tsc

    - name: Run
      run: |
        tsc && npm run start


